# Generated by Django 5.2.5 on 2025-08-22 12:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(blank=True, help_text='Optional note for where this email came from', max_length=120)),
                ('raw_text', models.TextField(blank=True)),
                ('eml_file', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['eml'])])),
                ('from_addr', models.CharField(blank=True, max_length=320)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(default='unknown', max_length=32)),
                ('score', models.FloatField(default=0.0)),
                ('explanations', models.JSONField(blank=True, default=list)),
                ('indicators', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
