# Generated by Django 5.2.5 on 2025-08-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsample',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='emailsample',
            old_name='raw_text',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='emailsample',
            name='eml_file',
        ),
        migrations.RemoveField(
            model_name='emailsample',
            name='explanations',
        ),
        migrations.RemoveField(
            model_name='emailsample',
            name='from_addr',
        ),
        migrations.RemoveField(
            model_name='emailsample',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='emailsample',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='emailsample',
            name='source_label',
        ),
        migrations.RemoveField(
            model_name='emailsample',
            name='verdict',
        ),
        migrations.AddField(
            model_name='emailsample',
            name='sender',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='emailsample',
            name='urls_text',
            field=models.TextField(blank=True, help_text='One URL per line or any pasted links.'),
        ),
        migrations.AlterField(
            model_name='emailsample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailsample',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailsample',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
