# Generated by Django 5.2.5 on 2025-08-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_emailsample_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsample',
            options={},
        ),
        migrations.RemoveField(
            model_name='emailsample',
            name='score',
        ),
        migrations.RemoveField(
            model_name='emailsample',
            name='urls_text',
        ),
        migrations.AddField(
            model_name='emailsample',
            name='is_phishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailsample',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailsample',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsample',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
