# Generated by Django 5.2.5 on 2025-08-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alter_emailsample_options_remove_emailsample_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsample',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
    ]
