# Generated by Django 5.2.5 on 2025-08-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_alter_emailsample_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsample',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
